newsletter/urls.py
from django.conf import settings
from django.urls import path, re_path

from .views import (
    confirmation,
    newsletter_create,
    newsletter_list,
    newsletter_send,
    newsletter_update,
    newsletter_view,
    stats,
    subscribe,
    thanks,
)

urlpatterns = [
    path('', subscribe, name='newsletter-subscribe'),
    path('thanks/', thanks, name='newsletter-thanks'),
    re_path(r'^(?P<token>[0-9a-f]{40})$', confirmation, name='newsletter-confirmation'),
    path('stats/', stats),
]

management_patterns = [
    path('', newsletter_list, name='newsletter-list'),
    path('add', newsletter_create, name='newsletter-create'),
    path('<int:pk>/', newsletter_view, name='newsletter-view'),
    path('<int:pk>/edit', newsletter_update, name='newsletter-edit'),
    path('<int:pk>/send', newsletter_send, name='newsletter-send'),
]

newsletter/models.py
import datetime
import hashlib
import random
import re
import smtplib
import subprocess
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import html2text
import mechanize
import requests
from ckeditor.fields import RichTextField
from combo.data.library import register_cell_class
from combo.data.models import CellBase
from django.conf import settings
from django.core.mail import send_mail
from django.db import IntegrityError, models
from django.template import loader
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.safestring import mark_safe
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _


class Subscriber(models.Model):
    email = models.EmailField(unique=False)
    inscription_date = models.DateTimeField(auto_now_add=True)
    is_validated = models.BooleanField(null=True)
    is_registered = models.BooleanField(null=True)
    password = models.CharField(max_length=100)
    bot_check1 = models.BooleanField(default=False)
    bot_check2 = models.BooleanField(default=False)
    user_agent = models.CharField(max_length=1000, blank=True)
    source_ip = models.CharField(max_length=100, blank=True)
    is_rejected = models.BooleanField(default=False)

    def __unicode__(self):
        return self.email

    def is_from_bot(self):
        return bool(self.bot_check1 or self.bot_check2)

    def send_confirmation_email(self):
        if self.is_from_bot():
            return
        self.password = hashlib.sha1(force_bytes(str(random.random()))).hexdigest()
        confirm_subject = loader.get_template('newsletter/confirmation_email_subject.txt')
        confirm_body = loader.get_template('newsletter/confirmation_email_body.txt')
        context = {'token': self.password}
        send_mail(
            confirm_subject.render(context).strip(),
            confirm_body.render(context),
            settings.NEWSLETTER_SENDER,
            [self.email],
        )
        self.is_validated = False
        self.save()

    def subscribe(self):
        newsletter_service = getattr(settings, 'NEWSLETTER_SERVICE', 'mailman')
        if newsletter_service == 'mailman':
            return self.subscribe_in_mailman()
        elif newsletter_service == 'mailman3':
            return self.subscribe_in_mailman3()
        elif newsletter_service == 'mailchimp':
            return self.subscribe_in_mailchimp()

    def subscribe_in_mailman(self):
        try:
            subprocess.run(['listadmin', '--add-member', self.email, settings.NEWSLETTER_NAME], check=True)
        except subprocess.CalledProcessError:
            # maybe an error because email is already registered?
            result = subprocess.run(
                ['listadmin', '-l', settings.NEWSLETTER_NAME], check=True, capture_output=True, text=True
            )
            if self.email in result.stdout.splitlines():
                self.is_registered = True
                self.save()
            return
        self.is_registered = True
        self.save()

    def subscribe_in_mailman3(self):
        # emulate browser to login and subscribe user
        br = mechanize.Browser()
        br.open(settings.NEWSLETTER_MAILMAN3_LIST_URL)
        br.follow_link(url_regex=re.compile('/accounts/login'))
        br.select_form(action=lambda x: '/login/' in x)
        br['login'] = settings.NEWSLETTER_MAILMAN3_LOGIN
        br['password'] = settings.NEWSLETTER_MAILMAN3_PASSWORD
        response = br.submit()
        assert br.find_link(url_regex=re.compile('/accounts/logout'))
        br.open(settings.NEWSLETTER_MAILMAN3_LIST_URL + 'mass_subscribe/')
        br.select_form(action=lambda x: '/mass_subscribe/' in x)
        br['emails'] = self.email
        br['pre_confirmed'] = ['on']
        br['pre_approved'] = ['on']
        br['pre_verified'] = ['on']
        br['send_welcome_message'] = ['False']
        response = br.submit()
        self.is_registered = True
        self.save()

    def subscribe_in_mailchimp(self):
        dc = settings.MAILCHIMP_DC
        apikey = settings.MAILCHIMP_APIKEY
        list_id = settings.MAILCHIMP_LIST_ID
        self.email = self.email.lower()

        email_hash = hashlib.md5(self.email.encode()).hexdigest()

        resp = requests.put(
            f'https://{dc}.api.mailchimp.com/3.0/lists/{list_id}/members/{email_hash}',
            auth=('key', apikey),
            json={
                'email_address': self.email,
                'status_if_new': 'subscribed',
            },
        )
        if resp.ok and resp.json().get('status') == 'subscribed':
            self.is_registered = True
            self.save()
        elif resp.status_code == 400:
            # maybe:
            # {'type': 'https://mailchimp.com/developer/marketing/docs/errors/',
            #  'title': 'Invalid Resource',
            #  'status': 400,
            #  'detail': "x@y has signed up to a lot of lists very recently; we're not allowing more signups for now",
            #  'instance': '...'
            # }
            print('  error subscribing', resp.json())
            self.is_rejected = True
            self.save()


class Newsletter(models.Model):
    class Meta:
        verbose_name = _('Newsletter')
        verbose_name_plural = _('Newsletters')
        ordering = ['date']

    subject = models.CharField(_('Title'), max_length=100)
    date = models.DateField(_('Date'))
    text = RichTextField(_('Text'), null=True, blank=True)

    expedition_datetime = models.DateTimeField(_('Expedition Date/time'), null=True, blank=True)

    def send(self):
        msg = MIMEMultipart('alternative')
        msg['Subject'] = self.subject
        msg['From'] = settings.NEWSLETTER_SENDER
        msg['To'] = '%s@%s' % (settings.NEWSLETTER_NAME, settings.NEWSLETTER_DOMAIN)

        h2t = html2text.HTML2Text()
        h2t.unicode_snob = True
        context = {
            'text_part': mark_safe(h2t.handle(self.text)),
            'html_part': mark_safe(self.text),
        }

        part1 = MIMEText(render_to_string('newsletter/email_body.txt', context), 'plain', _charset='utf-8')
        part2 = MIMEText(render_to_string('newsletter/email_body.html', context), 'html', _charset='utf-8')

        msg.attach(part1)
        msg.attach(part2)

        s = smtplib.SMTP('localhost')
        s.sendmail(msg['From'], msg['To'], msg.as_string())
        s.quit()

        self.expedition_datetime = datetime.datetime.now()
        self.save()

    def get_absolute_url(self):
        return reverse('newsletter-view', kwargs={'pk': self.id})


@register_cell_class
class NewsletterSubscribeFormCell(CellBase):
    default_template_name = 'newsletter/subscribe_form_cell.html'

    class Meta:
        verbose_name = _('Newsletter Subscribe Form')
        unique_together = [('page', 'uuid')]

    def get_cell_extra_context(self, context):
        from .forms import SubscribeForm

        context = super().get_cell_extra_context(context)
        context['newsletter_form'] = SubscribeForm()
        return context

newsletter/templates/newsletter/done.html
{% extends "base.html" %}

{% block title %}Newsletter{% endblock %}

{% block main %}
  <div class="padded">
    <p>
      Et voilà, c'est fait.
    </p>
  </div>
{% endblock %}

newsletter/templates/newsletter/email_body.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="x-apple-disable-message-reformatting">
    <title></title>
    <style>
      html,
      body {
        margin: 0 auto !important;
        padding: 0 !important;
        height: 100% !important;
        width: 100% !important;
      }

      * {
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%;
      }

      div[style*="margin: 16px 0"] {
        margin:0 !important;
      }

      table,
      td {
        mso-table-lspace: 0pt !important;
        mso-table-rspace: 0pt !important;
      }

      table {
        border-spacing: 0 !important;
        border-collapse: collapse !important;
        table-layout: fixed !important;
        margin: 0 auto !important;
      }
      table table table {
        table-layout: auto;
      }

      img {
        -ms-interpolation-mode:bicubic;
      }

      *[x-apple-data-detectors] {
        color: inherit !important;
        text-decoration: none !important;
      }

      .x-gmail-data-detectors,
      .x-gmail-data-detectors *,
      .aBn {
        border-bottom: 0 !important;
        cursor: default !important;
      }


      .button-link {
        text-decoration: none !important;
      }

      @media only screen and (min-device-width: 375px) and (max-device-width: 413px) { /* iPhone 6 and 6+ */
        .email-container {
          min-width: 375px !important;
        }
      }

      h2, h3 { font-family: "Reglo", sans-serif; }
      h3 { margin-bottom: 0; }
      h3 + p { margin-top: 0; }
      p strong { color: black; }
      h3 strong { text-transform: uppercase; color: blue; }
      p a { color: black; text-decoration: none; border-bottom: 1px dotted black; }
      p a:hover { border-bottom: 1px solid black; }
      img { max-width: 100%; }


    </style>

    <style>
      .button-td,
      .button-a {
        transition: all 100ms ease-in;
      }
      .button-td:hover,
      .button-a:hover {
        background: #333333 !important;
        border-color: #333333 !important;
      }
    </style>

  </head>
  <body width="100%" bgcolor="#F2F2F2" style="margin: 0; mso-line-height-rule: exactly;">
    <center style="width: 100%; background: #F2F2F2;">

      <div style="max-width: 600px; margin: auto;" class="email-container">
            <!--[if mso]>
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" align="center">
            <tr>
            <td>
            <![endif]-->

        <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
          <tr>
            <td style="padding: 20px 0; text-align: center; font-family: sans-serif;">
              <span style="font-size: 15px; line-height: 20px;"><img src="https://www.radiopanik.org/static/img/Radio_Panik_Logo_2016-01.png" alt="Radio Panik"/></span>
            </td>
          </tr>
        </table>

        <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">

          <tr>
            <td bgcolor="#3A3A3A">
              &nbsp;
            </td>
          </tr>

          <tr>
            <td bgcolor="#ffffff">
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                <tr>
                  <td style="overflow-wrap: break-word; word-wrap: break-word; padding: 40px; font-family: sans-serif; font-size: 15px; line-height: 22px; color: #333333;">

                    {% block content %}
                      {{html_part}}
                    {% endblock %}
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr>
            <td bgcolor="#3A3A3A">
              &nbsp;
            </td>
          </tr>

          <tr>
            <td height="10" style="font-size: 0; line-height: 0;">
              &nbsp;
            </td>
          </tr>

        </table>

        <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">
          <tr>
            <td style="padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; line-height:18px; text-align: center; color: #888888;" class="x-gmail-data-detectors">
              {% block footer %}
                <a href="https://tumulte.domainepublic.net/mailman3/postorius/lists/newsletter-panik.radiopanik.org/">Désabonnement</a>
              {% endblock %}
            </td>
          </tr>
        </table>
            <!--[if mso]>
            </td>
            </tr>
            </table>
            <![endif]-->
      </div>
    </center>
    <!-- adapted from http://tedgoas.github.io/Cerberus templates -->
  </body>
</html>

newsletter/templates/newsletter/newsletter_detail.html
{% extends "newsletter/newsletter_list.html" %}

{% block appbar %}
  <h2>{{ object.date }} - {{ object.subject }}</h2>
{% endblock %}

{% block content %}

  {% if object.expedition_datetime %}
    <p>Envoyée le {{ object.expedition_datetime }}</p>
  {% elif perms.newsletter.add_newsletter %}
    <p>
      <a class="button" href="{% url 'newsletter-edit' pk=object.id %}">Modifier</a>
      <a class="button" href="{% url 'newsletter-send' pk=object.id %}">Envoyer</a>
    </p>
  {% endif %}

  {% if newsletter.text %}
    <div class="section"><div>
      {{ newsletter.text|safe }}
    </div></div>
  {% endif %}

{% endblock %}

newsletter/templates/newsletter/newsletter_form.html
{% extends "newsletter/newsletter_list.html" %}

{% block extrascripts %}
  <script src="/static/ckeditor/ckeditor/ckeditor.js"></script>
  <script src="/static/ckeditor/ckeditor-init.js"></script>
{% endblock %}

{% block appbar %}
  {% if object %}
    <h2>{{ object.date }}</h2>
  {% else %}
    <h2>Nouvelle newsletter</h2>
  {% endif %}
{% endblock %}

{% block content %}
  <form method="post">
    <div id="form-content">
      {% csrf_token %}
      {{ form.as_p }}
    </div>
    {% block buttons %}
      <button class="enable-on-change">Enregistrer</button>
    {% endblock %}
  </form>
{% endblock %}

newsletter/templates/newsletter/newsletter_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Newsletters" %} | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>Newsletters</h2>
{% endblock %}

{% block more-user-links %}
  {{ block.super }}
  <a class="button icon-newsletter" href="{% url 'newsletter-list' %}">{% trans "Newsletters" %}</a>
{% endblock %}
{% block content %}

  {% if perms.newsletter.add_newsletter %}
    <p>
      <a class="button" href="{% url 'newsletter-create' %}">Nouvelle</a>
    </p>
  {% endif %}

  <div class="section">
    <ul class="emission-list">
      {% for newsletter in object_list %}
        <li><a href="{% url 'newsletter-view' pk=newsletter.id %}">{{ newsletter.date }}</a></li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

newsletter/templates/newsletter/subscribe_form_cell.html
{% load i18n %}
<form method="post" action="{% url 'newsletter-subscribe' %}" id="subscribe-form">
  {% include "newsletter/subscriber_form_content.html" %}
</form>

newsletter/templates/newsletter/subscriber_form.html
{% extends "base.html" %}

{% block title %}Newsletter{% endblock %}

{% block main %}
  <div class="padded">
    <form method="post" class="big center" id="subscribe-form">
      {% include "newsletter/subscriber_form_content.html" %}
    </form>
  </div>
{% endblock %}

newsletter/templates/newsletter/subscriber_form_content.html
{% load i18n %}

{% csrf_token %}

{% block newsletter-text %}
{% endblock %}

{% block newsletter-form-content %}
  <label for="email" class="sr-only">{% trans "your email address" %}</label>
  <input required name="email" id="email" type="email" placeholder="{% trans "your email address" %}">
  <div style="display: none;">
    <label for="validation"><input type="checkbox" name="validation" id="validation"
      >{% trans "Checking this will prevent subscribing." %}</label>
    <label for="validation2"><input type="checkbox" name="validation2" id="validation2"
      >{% trans "On the other hand this checkbox must be checked (sorry if you have javascript disabled)" %}</label>
    <script>
      (function() {
        const checkbox = document.getElementById('validation2');
        checkbox.checked = true;
      })();
    </script>
  </div>
  <button>{% trans 'Subscribe' %}</button>
{% endblock %}

newsletter/templates/newsletter/subscriber_form_embed.html
{% load i18n %}
<form method="post" action="{% url 'newsletter-subscribe' %}" class="marged" id="subscribe-form">
  {% include "newsletter/subscriber_form_content.html" %}
</form>

newsletter/templates/newsletter/thanks.html
{% extends "base.html" %}

{% block title %}Newsletter{% endblock %}

{% block main %}
  <div class="padded">
    <p>
      Un courriel de confirmation vous a été envoyé; suivez l'adresse qui y
      est contenue pour valider votre abonnement.
    </p>
  </div>
{% endblock %}